### ISSUE TITLE
Question about ShellPipe.cls

### ISSUE THREAD

**Issue by Greedquest** [M2000Interpreter/Environment#1]
I know this is tangential to your project.

I'm wondering how "async" the ShellPipe is? 

I want to use it in vba, I was expecting something along the lines of

```vba
Private WithEvents SP as ShellPipe

Sub RunProcess()
    Set SP = New ShellPipe
    SP.Run "programmeWithOuput.exe"
End Sub

Private Sub processPipe_DataArrival(ByVal CharsTotal As Long)
    Debug.Print "Got Data", length, SP.GetData(CharsTotal)
End Sub
```

However when I create an isntance of that class (in a module level variable so I don't lose it), the event handler is never triggered. Indeed looking more closely it seems there is an "EventLoop" method to call to get the pipe to check for new data - this isn't really async and is more like polling. Is there not a winapi callback you can use to listen for new data truly asynchronously?

Or am I being dumb and using it wrong? Basically I want to stream output from a child process into a userform text control.

**Comment by M2000Interpreter** [comment]
1. The original creator, user of vbforums.com  dilettante,  of ShellPipe as control (not that as a class) can be found in [vbforums](https://www.vbforums.com/showthread.php?660014-VB6-ShellPipe-quot-Shell-with-I-O-Redirection-quot-control&highlight=shellpipe)
2.  See message  [#15](https://www.vbforums.com/showthread.php?660014-VB6-ShellPipe-quot-Shell-with-I-O-Redirection-quot-control&p=5494747&viewfull=1#post5494747) about the Handler2 program (you find it in Info.gsb file) which call the cmd.exe using /k option. Also I use the shellpipe for communicate with a stockfish 12 chess engine, for 50ms to 200ms response time. For chess I didn't use WithEvents. I send a FEN string (the current position on chess board), and then send a command about the time to response, and then I use an Every loop (like a timer but insert it synchronously after the commands. At that event loop i call ProcessLoop which isn't blocking, and examine the While Engine.HasLine to GetLine from Engine and inspect if there is the word "bestmove" (so the line has to filled from the engine) and this end the reading (the multiple GetLines) and from that "bestmove..." line the FEN (chess board new position) returned.

In chess first I do a Gosub initengine  (a simple routine like BASIC's old GOSUB). Then I use a simple function (is static and has the same name space as the module's so Engine is at the same scope.
```
Function GetMove$(Fen$)
	local aLine$
	method Engine, "SendLine" , "position fen "+Fen$
	method Engine, "SendLine" ,"go movetime"+str$(random(50, 200))
	every 50 {
		Method Engine, "ProcessLoop"
		if not Engine.Active then exit
		while  Engine.HasLine
			method Engine, "GetLine" as aLine$
			if left$(aLine$,8)="bestmove" then exit
                     End While
		if left$(aLine$,8)="bestmove" then =piece$(aLine$," ", 2) : exit
	}		
End Function
initengine:
declare Engine SHELLPIPE
with Engine, "Active" as Engine.Active, "Hasline" as Engine.HasLine
Method Engine, "Run",  enginepath$ as OkEngine
if OkEngine=0 then  Method Engine, "SendLine", "ucinewgame"
Return
```

3. For your program you need a timer to execute the ProcessLoop (which isn't blocking)

4. This is a demo I wrote based on Handler2. The WithEvents removed. The Event DataArival can't be used, because fired when we have to get "all" data in a while loop (and then a new DateArival fired). So for this demo I use Threads which are code in timers, or loops based on timers (there are two type of Thread.Plan but here we use the default Sequential, so each thread executed as is and then pass execution to any other thread.

So now we have an InputBox to wait to place a command, and at the same time we get all lines from previous executed commands (like Dir /w or Help), plus we have a clock displayed as a background task. The InputBox isn't blocking in M2000 because there is a wait function which allow threads to executed (the M2000 has task manager  for this).

The analogy for VB6 can be found on timers on a form. You can make the same program, using timers instead of M2000 Threads. Instead of inputbox you can use a nice textbox (and a list box for drawing text lines - or you can study the way I use a PictureBox for mimic a console  in M2000 (RevisionPrint() is the function who execute the Print statement).


```
Thread.Plan Sequential 
Escape Off
cls 5
Form 80, 50
Pen 15 {
	Print "Demo: Using a console program from M2000, using ShellPipe internal object"
	Print "Press Esc to exit, or write Exit and press enter"
}
cls, 2
Declare SP SHELLPIPE
with SP, "Active" as IsActive, "Hasline" as Sp.HasLine
Method SP, "Run","cmd.exe /k" as ok
Wait 200
Show
integer x, y
If ok=0 then
    Method SP, "SendLine", "Dir"
     lastcomm$=""
    comm$=""
    thread {
        (x, y)=(pos, row)
        pen 15 {print @(width-11, 1, width-1, 2, 5), str$(now,"hh:nn:ss")}
        cursor x, y
    } as dd interval 1000/60
    Thread {
	if Sp.HasLine then {
		method Sp, "GetLine" as aLine$
		if right$(aline$, len(lastcomm$)+1)<>">"+lastcomm$ then
			Print #-2, aLine$
		end if
        }       
    }  as cc interval 30
    boolean GETOUT=FALSE
    thread {
    		if ASK("Chid","Demo2","ok", "Cancel", , "") =1 then
    			read comm$ 
        		Print "(child)>";
        		Pen 15 {? comm$}
        		Print
        		Method SP, "SendLine", comm$
        		lastcomm$=comm$
        		thead this interval 100
              else
                  GETOUT=true
                  thread this erase
             end if   
    } as bb interval 10
   main.task 100 {
       Method Sp, "ProcessLoop"
    	if not IsActive then exit
    	if GETOUT then exit
    }
    THREADS ERASE
end if
Declare SP nothing
```
